POST /residents HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "name" : "남남일",
  "residentRegistrationNumber" : "123456-1234567",
  "genderCode" : "남",
  "birthDate" : "2022-07-22T07:22:00",
  "birthPlaceCode" : "병원",
  "registrationBaseAddress" : "전라남도 나주시 금계23번길"
}
###
PUT /residents/6 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "name" : "이선미",
  "residentRegistrationNumber" : "851205-1234566",
  "genderCode" : "여",
  "birthDate" : "1985-12-05T22:01:00",
  "birthPlaceCode" : "병원",
  "registrationBaseAddress" : "전라남도 나주시 금계23번길",
  "deathDate" : "2023-03-22T10:24:10",
  "deathPlaceCode" : "병원",
  "deathPlaceAddress" : "경기도 수원시 팔달구 효원로 7번길"
}

###
POST /residents/8/relationship
Host: localhost:8080
Content-Type: application/json

{
  "familySerialNumber": 4,
  "relationship": "부"
}

###
PUT /residents/8/relationship/4
Host: localhost:8080
Content-Type: application/json

{
  "relationship": "삼촌"
}

###
DELETE /residents/8/relationship/6
Host: localhost:8080
Content-Type: application/json

### 출생등록
POST /residents/4/birth
Host: localhost:8080
Content-Type: application/json

{
  "residentSerialNumber" : 8,
  "birthDeathTypeCode" : "출생",
  "birthReportQualificationsCode" : "부",
  "phoneNumber" : "010-2345-6789"
}

###
PUT /residents/4/birth/8
Host: localhost:8080
Content-Type: application/json

{
  "residentSerialNumber" : 8,
  "birthDeathTypeCode" : "출생",
  "birthReportQualificationsCode" : "부",
  "emailAddress" : "12342@email.com",
  "phoneNumber" : "010-2345-5555"
}
###
DELETE /residents/4/birth/8
Host: localhost:8080
Content-Type: application/json


### 사망등록
POST /residents/4/death
Host: localhost:8080
Content-Type: application/json

{
  "residentSerialNumber" : 6,
  "birthDeathTypeCode" : "사망",
  "deathReportQualificationsCode" : "처제",
  "phoneNumber" : "010-2345-6789"
}
###
PUT /residents/4/death/6
Host: localhost:8080
Content-Type: application/json

{
  "residentSerialNumber" : 6,
  "birthDeathTypeCode" : "사망",
  "deathReportQualificationsCode" : "처제",
  "emailAddress" : "12342@email.com",
  "phoneNumber" : "010-2345-5555"
}

###
DELETE /residents/4/death/6
Host: localhost:8080
Content-Type: application/json

### 세대 등록
POST /household
Host: localhost:8080
Content-Type: application/json

{
  "residentId" : 2,
  "householdCompositionDate" : "2009-10-31",
  "compositionReasonCode" : "전입",
  "currentHouseMovementAddress" : "경기도 성남시 분당구 불정로 90번길"
}

### 세대 삭제
DELETE /household/2
Host: localhost:8080
Content-Type: application/json

### 세대 전입 주소 등록
POST /household/2/movement
Host: localhost:8080
Content-Type: application/json

{
  "houseMovementReportDate" : "20071031",
  "houseMovementAddress" : "서울시 동작구 상도로 940번길 ",
  "lastAddressYN" : "Y"
}

### 세대 전입 주소 수정
PUT /household/2/movement/20071031
Host: localhost:8080
Content-Type: application/json

{
 "houseMovementAddress" : "서울시 동작구 상도로 940번길 ",
  "lastAddressYN" : "N"
}

### 세대 전입 주소 삭제
DELETE /household/2/movement/20071031
Host: localhost:8080
Content-Type: application/json
